# Generated by Django 2.1.2 on 2018-10-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'managed': True},
        ),
    ]
