# Generated by Django 2.1.2 on 2018-11-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181026_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'managed': False},
        ),
    ]
