# Generated by Django 2.1.2 on 2018-11-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20181114_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspnetusers',
            options={'managed': True},
        ),
    ]
