# Generated by Django 2.1.2 on 2018-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20181114_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspnetusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aspnetusers',
            name='username',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
