# Generated by Django 2.1.2 on 2018-11-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_projectdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaditems',
            options={'managed': True},
        ),
    ]
