# Generated by Django 2.1.2 on 2018-11-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20181119_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='projectid',
            field=models.CharField(max_length=20),
        ),
    ]
