# Generated by Django 2.1.2 on 2018-11-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20181120_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'managed': True},
        ),
    ]
