# Generated by Django 2.1.2 on 2018-11-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20181121_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='isassigned',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='leads',
            name='receivedon',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
