# Generated by Django 2.1.2 on 2018-11-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20181121_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='locality',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='projectname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
